//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightLogNet.Operation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlightLogNet.Operation.ReportLocalization", typeof(ReportLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copilot.
        /// </summary>
        internal static string CopilotColumn {
            get {
                return ResourceManager.GetString("CopilotColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string DateColumn {
            get {
                return ResourceManager.GetString("DateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightId.
        /// </summary>
        internal static string FlightIdColumn {
            get {
                return ResourceManager.GetString("FlightIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doba letu.
        /// </summary>
        internal static string FlightLengthColumn {
            get {
                return ResourceManager.GetString("FlightLengthColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GliderID.
        /// </summary>
        internal static string GliderIdColumn {
            get {
                return ResourceManager.GetString("GliderIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immatriculation.
        /// </summary>
        internal static string ImmatriculationColumn {
            get {
                return ResourceManager.GetString("ImmatriculationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandingTime.
        /// </summary>
        internal static string LandingTimeColumn {
            get {
                return ResourceManager.GetString("LandingTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        internal static string PilotColumn {
            get {
                return ResourceManager.GetString("PilotColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeoffTime.
        /// </summary>
        internal static string TakeoffTimeColumn {
            get {
                return ResourceManager.GetString("TakeoffTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string TaskColumn {
            get {
                return ResourceManager.GetString("TaskColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TowplaneID.
        /// </summary>
        internal static string TowplaneIdColumn {
            get {
                return ResourceManager.GetString("TowplaneIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeColumn {
            get {
                return ResourceManager.GetString("TypeColumn", resourceCulture);
            }
        }
    }
}
